name: Deploy Hugo Site
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.8'
          extended: true
      - name: Build Hugo site
        run: |
          cd matteodegobbi
          hugo --gc --minify --cleanDestinationDir
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: matteodegobbi/matteodegobbi.github.io
          publish_dir: ./matteodegobbi/public
          publish_branch: main
